### ISSUE TITLE
Accessories not showing up in HomeKit

### ISSUE THREAD

**Issue by gavinkleckner** [BewhiskeredBard/homebridge-alexa-player#209]
I had this plug-in for a while and it was working great but then I decided I didn’t want the Amazon echos in HomeKit but now I want them again and I have everything working except when I go into the HomeKit app they don’t show up here are some photos that show everything happening some help would be greatly appreciated by the way I’m using a raspberry pi three
![18FA17A6-C4F3-4898-A017-11D257F49800](https://user-images.githubusercontent.com/57422502/117398501-1a1f1600-aec4-11eb-8976-ff0fe343c5f2.png)
![F4F59A16-9478-49E2-97A7-A8A774CB7CD3](https://user-images.githubusercontent.com/57422502/117398503-1ab7ac80-aec4-11eb-9650-aadfa616fea0.png)
![EA76AB3A-5856-4051-83BF-AC252068D5DB](https://user-images.githubusercontent.com/57422502/117398504-1b504300-aec4-11eb-81a5-6b0912b5f887.png)
![FC7F98BE-C9A8-4D33-A261-1A5270523E12](https://user-images.githubusercontent.com/57422502/117398505-1be8d980-aec4-11eb-82d1-74082987bcb2.png)
![A8121AE2-CEC6-4FA0-89A0-A41410CB9E0F](https://user-images.githubusercontent.com/57422502/117398506-1be8d980-aec4-11eb-8fe6-a3741c5fed82.png)

**Comment by schweppy** [comment]
Hi, same problem for me. Tried this plugin last year on a couple of echos but removed them, now wanting to try the plugin again with the same echos. They appear as above in the homebridge UI but do not appear in the home app. Only the echos I didn't use last time are appearing.

Assume this is a persist/accessory issue in the homebridge folder but have too many other accessories to work out which persist to delete! Any other ideas?

Many thanks

Andy

**Comment by BHAEK** [comment]
Exactly the same problem... first added to Home app, than removed. 
I tried to re-add my "Echo show" but Home app can't find it.
Echo show is showed in homebridge accessories if I look for it in "devices" section in the web-gui

**Comment by JanVanOostenrijk** [comment]
Had the exact same issue: Tried this plugin a few months ago, removed all the speakers then because of some housekeeping work, now wanting to retry this plugin but none of the speakers showed up except for the one Echo I got since.

After some digging around, I found the solution:
Even if devices do not show up in the Home App anymore, they're still marked as "paired" within Homebridge. To unpair devices that are no longer paired, in the Homebridge Config UI go to "Homebridge Settings" (three dots-menu on upper right corner), scroll down to "Unpair Bridges / Cameras / TVs / External Accessories" and click the button with an arrow in it on the right. Here, unpair all Echo devices and restart Homebridge. You should be able to see all devices in the "Add Accessory" dialogue in the Home App again.
